name: Docker Build and Publish

on:
  push:
    branches:
      - main
      - develop
      - staging
    tags:
      - 'v*.*.*'  # SemVer: triggers on v1.2.3
  workflow_dispatch:

permissions:
  contents: read
  id-token: write  # required for OIDC (if using)
  packages: write

jobs:
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_type == 'tag' && 'production' || 'preview' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=raw,value=prod-{{version}},enable={{startsWith(github.ref, 'refs/tags/v')}}
            type=raw,value=latest,enable={{github.ref == 'refs/heads/main'}}
            type=raw,value=dev-latest,enable={{github.ref == 'refs/heads/develop'}}
            type=raw,value=staging-latest,enable={{github.ref == 'refs/heads/staging'}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: docker
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Generate Release Notes
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
